# Generated by Django 3.1.6 on 2021-02-18 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type_name', models.CharField(max_length=100, verbose_name='Наименование типа растения')),
            ],
        ),
        migrations.CreateModel(
            name='WindowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_type_name', models.CharField(max_length=100, verbose_name='Наименование типа окна для растнения')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255, verbose_name='Наименование растения')),
                ('plant_requirements', models.TextField(verbose_name='Требование по уходу')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.planttype')),
                ('plant_window_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.windowtype')),
            ],
        ),
    ]
